### ISSUE TITLE
Cannot create table with UNIQUE or PRIMARY KEY

### ISSUE THREAD

**Issue by fermuch** [spatialdude/usqlite#10]
The following SQL

```sql
CREATE TABLE IF NOT EXISTS login(
  key TEXT NOT NULL PRIMARY KEY,
  name TEXT
);
```

Gives the error:

```
usqlite_Error: malformed database schema (sqlite_autoindex_login_1) - orphan index
```

Same happens if I try to set a column as UNIQUE.

**Comment by spatialdude** [comment]
This error is caused by the [`SQLITE_OMIT_ATTACH`](https://sqlite.org/compile.html) option. This option is now disabled by default - https://github.com/spatialdude/usqlite/blob/131fb3c68751ffe46a55633adcf753a068924bb1/usqlite_config.h#L39
