### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by emile-cronje** [spatialdude/usqlite#12]
Good day

I am following the getting started section on https://github.com/spatialdude/usqlite

I get the following error when following the instructions on https://github.com/spatialdude/usqlite/wiki/unix

sqlite/usqlite_module.c:127:35: error: ‘mp_obj_type_t’ {aka ‘const struct _mp_obj_type_t’} has no member named ‘make_new’

Ubuntu 22.04

Regards

**Comment by l-atome** [comment]
Perhaps watch my new post ... https://github.com/spatialdude/usqlite/issues/13 ... three days to adapt this beautiful code with new update os

**Comment by spatialdude** [comment]
@emile-cronje @l-atome Please try out the latest version of µsqlite module. It has been updated to support the latest version of MicroPython (thanks @dpgeorge) as well as updated to the latest version of SQLite (3.40.1).
