### ISSUE TITLE
usqlite does not compile

### ISSUE THREAD

**Issue by tamaslukacs** [spatialdude/usqlite#3]
Hi!
I think there is a problem with the latest edits.. could you please check?
[ 98%] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/__/modules/usqlite/usqlite_vfs.c.obj
/home/ltomi91/Desktop/micro/micropythonrep/micropython/ports/esp32/modules/usqlite/usqlite_file.c: In function 'usqlite_file_exists':
/home/ltomi91/Desktop/micro/micropythonrep/micropython/ports/esp32/modules/usqlite/usqlite_file.c:36:19: error: implicit declaration of function 'mp_module_get'; did you mean 'mp_locals_get'? [-Werror=implicit-function-declaration]
     mp_obj_t os = mp_module_get(MP_QSTR_uos);
                   ^~~~~~~~~~~~~
                   mp_locals_get
/home/ltomi91/Desktop/micro/micropythonrep/micropython/ports/esp32/modules/usqlite/usqlite_file.c:36:19: warning: initialization of 'mp_obj_t' {aka 'void *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
/home/ltomi91/Desktop/micro/micropythonrep/micropython/ports/esp32/modules/usqlite/usqlite_file.c: In function 'usqlite_file_delete':
/home/ltomi91/Desktop/micro/micropythonrep/micropython/ports/esp32/modules/usqlite/usqlite_file.c:237:38: warning: passing argument 1 of 'usqlite_method' makes pointer from integer without a cast [-Wint-conversion]
     mp_obj_t remove = usqlite_method(mp_module_get(MP_QSTR_uos), MP_QSTR_remove);
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ltomi91/Desktop/micro/micropythonrep/micropython/ports/esp32/modules/usqlite/usqlite.h:35,
                 from /home/ltomi91/Desktop/micro/micropythonrep/micropython/ports/esp32/modules/usqlite/usqlite_file.c:25:
/home/ltomi91/Desktop/micro/micropythonrep/micropython/ports/esp32/modules/usqlite/usqlite_utils.h:47:48: note: expected 'const mp_obj_module_t *' {aka 'const struct _mp_obj_module_t *'} but argument is of type 'int'
 mp_obj_t usqlite_method(const mp_obj_module_t *module, qstr name);
                         ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
cc1: some warnings being treated as errors
make[3]: *** [esp-idf/main/CMakeFiles/__idf_main.dir/build.make:3431: esp-idf/main/CMakeFiles/__idf_main.dir/__/modules/usqlite/usqlite_file.c.obj] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/ltomi91/Desktop/micro/micropythonrep/micropython/ports/esp32/build-GENERIC'
make[2]: *** [CMakeFiles/Makefile2:4672: esp-idf/main/CMakeFiles/__idf_main.dir/all] Error 2
make[2]: Leaving directory '/home/ltomi91/Desktop/micro/micropythonrep/micropython/ports/esp32/build-GENERIC'
make[1]: *** [Makefile:149: all] Error 2
make[1]: Leaving directory '/home/ltomi91/Desktop/micro/micropythonrep/micropython/ports/esp32/build-GENERIC'
make failed with exit code 2
make: *** [Makefile:34: all] Error 2

**Comment by spatialdude** [comment]
Thanks @tamaslukacs I've updated to code work with the latest changes in the MicroPython repo.
